-- Seed data for Cybersecurity Portfolio
-- Run this after schema.sql in Supabase SQL Editor

-- Sample Projects (7)
INSERT INTO projects (name, description, tech, github, demo, category) VALUES
('UniTie', 'A full-stack hackathon platform for managing events, teams, registrations, and mentorship. Built for universities and organizations.', ARRAY['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'PostgreSQL'], 'https://github.com/yourusername/unitie', 'https://unitie.app', 'Web'),
('Blockchain Forensics Tool', 'Smart contract analysis and transaction tracing tool for investigating blockchain-based crimes and DeFi exploits.', ARRAY['Python', 'Web3.py', 'Solidity', 'React', 'ethers.js'], 'https://github.com/yourusername/blockchain-forensics', NULL, 'Blockchain'),
('Suricata IDS Dashboard', 'Real-time network intrusion detection system with custom rules and visualization dashboard for SOC analysts.', ARRAY['Suricata', 'Python', 'FastAPI', 'React', 'Elasticsearch'], 'https://github.com/yourusername/suricata-dashboard', NULL, 'Security'),
('Agentic Wazuh SOC', 'NLP-powered threat hunting assistant integrated with Wazuh SIEM for automated alert correlation and response recommendations.', ARRAY['Python', 'LangChain', 'Wazuh', 'OpenAI', 'FastAPI'], 'https://github.com/yourusername/agentic-wazuh', NULL, 'AI'),
('File Integrity Monitor', 'Real-time file system monitoring tool with hash verification, change detection, and alerting capabilities.', ARRAY['Python', 'SQLite', 'Watchdog', 'FastAPI'], 'https://github.com/yourusername/file-monitor', NULL, 'Security'),
('Home Lab Infrastructure', 'Personal cybersecurity lab with virtualized network, honeypots, SIEM, and various security tools for research and training.', ARRAY['Proxmox', 'pfSense', 'Docker', 'Wazuh', 'Suricata'], 'https://github.com/yourusername/homelab', NULL, 'Security'),
('OSINT Toolkit', 'Automated OSINT data collection and analysis toolkit for digital footprinting and reconnaissance operations.', ARRAY['Python', 'Selenium', 'BeautifulSoup', 'SQLite'], 'https://github.com/yourusername/osint-toolkit', NULL, 'Security');

-- Sample CTF Writeups (10)
INSERT INTO writeups (title, slug, category, difficulty, tools, content_md, published) VALUES
('SQL Injection in Login Form - HackTheBox', 'sql-injection-htb-login', ARRAY['Web'], 'Easy', ARRAY['Burp Suite', 'sqlmap'], E'# SQL Injection in Login Form\n\n## Challenge Overview\nA vulnerable login form that doesn''t sanitize user input.\n\n## Solution\n\n### Step 1: Identify the Vulnerability\nUsing Burp Suite, I intercepted the login request:\n\n```http\nPOST /login HTTP/1.1\nusername=admin&password=test\n```\n\n### Step 2: Test for SQLi\n```sql\nadmin'' OR ''1''=''1\n```\n\n### Step 3: Extract Data\nUsed sqlmap for automated extraction:\n```bash\nsqlmap -u "http://target/login" --data "username=admin&password=test" --dbs\n```\n\n## Flag\n`HTB{sql_1nj3ct10n_m4st3r}`', true),

('XSS via SVG Upload - CTFtime', 'xss-svg-upload-ctftime', ARRAY['Web'], 'Medium', ARRAY['Burp Suite', 'Custom Script'], E'# XSS via SVG Upload\n\n## Discovery\nThe application allowed SVG file uploads for profile pictures.\n\n## Payload\n```xml\n<svg xmlns="http://www.w3.org/2000/svg">\n  <script>alert(document.cookie)</script>\n</svg>\n```\n\n## Impact\nStored XSS affecting all users who view the profile.', true),

('RSA Weak Key Attack - PicoCTF', 'rsa-weak-key-picoctf', ARRAY['Crypto'], 'Medium', ARRAY['Python', 'RsaCtfTool'], E'# RSA Weak Key Attack\n\n## Analysis\nThe public key had a small prime factor.\n\n```python\nimport sympy\nn = 123456789...\nfactors = sympy.factorint(n)\n```\n\n## Solution\nFactored n using Fermat''s method and reconstructed private key.', true),

('OSINT Geolocation Challenge - OSINTCTF', 'osint-geolocation-challenge', ARRAY['OSINT'], 'Hard', ARRAY['Google Earth', 'Bellingcat Toolkit'], E'# Geolocation from Image Metadata\n\n## Approach\n1. Extracted EXIF data\n2. Analyzed shadows for time estimation\n3. Cross-referenced landmarks\n\n## Tools Used\n- exiftool for metadata\n- Google Earth for verification', true),

('Buffer Overflow Basics - OverTheWire', 'buffer-overflow-overthewire', ARRAY['Pwn'], 'Easy', ARRAY['GDB', 'pwntools', 'ROPgadget'], E'# Buffer Overflow Exploitation\n\n## Vulnerability\nStack-based buffer overflow in gets() function.\n\n```c\nvoid vulnerable() {\n    char buffer[64];\n    gets(buffer); // No bounds checking!\n}\n```\n\n## Exploit\n```python\nfrom pwn import *\npayload = b"A" * 72 + p64(win_addr)\n```', true),

('JWT None Algorithm Attack', 'jwt-none-algorithm', ARRAY['Web'], 'Easy', ARRAY['jwt_tool', 'Burp Suite'], E'# JWT None Algorithm Bypass\n\n## The Vulnerability\nServer accepted JWT with algorithm set to "none".\n\n## Steps\n1. Decode token\n2. Change alg to "none"\n3. Modify payload\n4. Remove signature\n\n```python\nheader = {"alg": "none", "typ": "JWT"}\n```', true),

('Memory Forensics - Volatility CTF', 'memory-forensics-volatility', ARRAY['Forensics'], 'Hard', ARRAY['Volatility3', 'strings'], E'# Memory Dump Analysis\n\n## Challenge\nAnalyze memory dump to find hidden malware.\n\n## Process\n```bash\nvol3 -f memory.raw windows.pstree\nvol3 -f memory.raw windows.malfind\n```\n\n## Finding\nInjected shellcode in svchost.exe', true),

('Steganography - Hidden Message', 'steganography-hidden-message', ARRAY['Forensics', 'Misc'], 'Easy', ARRAY['steghide', 'zsteg', 'binwalk'], E'# Hidden Data in Image\n\n## Initial Analysis\n```bash\nfile challenge.png\nbinwalk challenge.png\n```\n\n## Extraction\n```bash\nsteghide extract -sf image.jpg\n```\n\nPassword was in the image metadata!', true),

('Reverse Engineering Malware', 'reverse-engineering-malware', ARRAY['Pwn', 'Forensics'], 'Insane', ARRAY['Ghidra', 'x64dbg', 'IDA Pro'], E'# Malware Analysis\n\n## Static Analysis\n1. Identified packer (UPX)\n2. Unpacked binary\n3. Analyzed in Ghidra\n\n## Findings\n- C2 communication obfuscated\n- XOR key: 0x42\n- Anti-debugging checks', true),

('SSRF to Cloud Metadata', 'ssrf-cloud-metadata', ARRAY['Web'], 'Medium', ARRAY['Burp Suite', 'curl'], E'# SSRF Exploitation\n\n## Discovery\nImage fetch feature accepts arbitrary URLs.\n\n## Payload\n```\nhttp://169.254.169.254/latest/meta-data/iam/security-credentials/\n```\n\n## Impact\nRetrieved AWS credentials from EC2 metadata service.', true);

-- Sample Blog Posts (5)
INSERT INTO posts (title, slug, excerpt, content_md, tags, published, published_at, reading_time) VALUES
('Building a Home Lab for Security Research', 'building-home-lab-security', 'A comprehensive guide to setting up your own cybersecurity home lab using Proxmox, virtual machines, and open-source security tools.', E'# Building a Home Lab for Security Research\n\nEvery security professional needs a safe environment to practice and experiment.\n\n## Hardware Requirements\n- 32GB RAM minimum\n- 1TB SSD\n- Dual NIC\n\n## Software Stack\n1. **Proxmox** - Hypervisor\n2. **pfSense** - Firewall\n3. **Wazuh** - SIEM\n4. **Suricata** - IDS\n\n## Network Segmentation\n\n```\nInternet → pfSense → VLAN10 (Prod) → VLAN20 (Lab) → VLAN30 (Malware)\n```\n\n## Getting Started\n\nFirst, install Proxmox on bare metal...', ARRAY['security', 'homelab', 'tutorial'], true, now(), 8),

('Understanding React2Shell (CVE-2025-55182)', 'understanding-react2shell-cve', 'Deep dive into the critical React Server Components vulnerability that allows unauthenticated remote code execution.', E'# Understanding React2Shell\n\nCVE-2025-55182 is a critical vulnerability in React Server Components.\n\n## How It Works\n\nThe vulnerability exploits the Flight protocol deserialization.\n\n```javascript\n// The vulnerable pattern\nconst exports = moduleTable[id];\nconst fn = exports[name]; // No validation!\n```\n\n## Affected Versions\n- Next.js 15.x < 15.5.7\n- React 19.x with RSC\n\n## Mitigation\n\nUpgrade to patched versions immediately.', ARRAY['security', 'vulnerability', 'react', 'nextjs'], true, now(), 10),

('OSINT Techniques for Investigating Crypto Scams', 'osint-crypto-scam-investigation', 'How to use open-source intelligence techniques to track down cryptocurrency fraudsters.', E'# Investigating Crypto Scams with OSINT\n\n## Starting Points\n\n1. Wallet addresses\n2. Transaction history\n3. Social media profiles\n\n## Tools\n\n- **Etherscan** - Blockchain explorer\n- **Breadcrumbs** - Visual transaction analysis\n- **Maltego** - Entity relationship mapping\n\n## Case Study\n\nTracking a rug pull from contract deployment to exchange cashout...', ARRAY['osint', 'blockchain', 'investigation'], true, now(), 12),

('Setting Up Wazuh for EDR and SIEM', 'wazuh-edr-siem-setup', 'Complete guide to deploying Wazuh as your open-source endpoint detection and response solution.', E'# Wazuh Deployment Guide\n\n## Components\n\n- **Wazuh Server** - Central management\n- **Wazuh Indexer** - Data storage\n- **Wazuh Dashboard** - Visualization\n\n## Installation\n\n```bash\ncurl -sO https://packages.wazuh.com/4.7/wazuh-install.sh\nsudo bash ./wazuh-install.sh -a\n```\n\n## Agent Deployment\n\nDeploy agents to all endpoints...', ARRAY['security', 'siem', 'tutorial', 'wazuh'], true, now(), 15),

('Web3 Security: Smart Contract Auditing Basics', 'web3-smart-contract-auditing', 'Introduction to auditing Solidity smart contracts for common vulnerabilities.', E'# Smart Contract Auditing\n\n## Common Vulnerabilities\n\n1. **Reentrancy**\n2. **Integer Overflow**\n3. **Access Control**\n4. **Front-running**\n\n## Tools\n\n- Slither\n- Mythril\n- Foundry\n\n## Example: Reentrancy\n\n```solidity\n// Vulnerable\nfunction withdraw() public {\n    uint amount = balances[msg.sender];\n    (bool success,) = msg.sender.call{value: amount}("");\n    balances[msg.sender] = 0; // Too late!\n}\n```', ARRAY['blockchain', 'security', 'web3', 'tutorial'], true, now(), 7);
